imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources:
          - 'AcmeDemoBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8

    dbal:
        default_connection:   CSI_DEV
        #default_connection:   CSI_OLD
        connections:
            CSI_OLD:
                driver:   pdo_sqlsrv
                host:     10.60.99.237\DPS_SERVER
                port:     null
                dbname:   CSI
                user:     DPS_User
                password: CargoFPT
                charset:  UTF8
            CSI_DEV:
                driver:   pdo_sqlsrv
                host:     10.60.99.237\DPS_SERVER
                port:     null
                dbname:   CSI_DEV
                user:     DPS_User
                password: CargoFPT
                charset:  UTF8
            CSI_PROD:
                driver:   pdo_sqlsrv
                host:     10.60.99.237\DPS_SERVER
                port:     null
                dbname:   CSI_PROD
                user:     DPS_User
                password: CargoFPT
                charset:  UTF8
            Flight_and_RT_DB:
                driver:   pdo_sqlsrv
                host:     10.60.99.237\DPS_SERVER
                port:     null
                dbname:   Flight_and_RT_DB
                user:     DPS_User
                password: CargoFPT
                charset:  UTF8
            zz_Price:
                driver:   pdo_sqlsrv
                host:     10.60.99.237\DPS_SERVER
                port:     null
                dbname:   zz_Price
                user:     DPS_User
                password: CargoFPT
                charset:  UTF8
            idefix_cafeed:
                driver:   pdo_mysql
                host:     ccc-srv2.france.ad.airfrance.fr
                port:     3306
                dbname:   cafeed
                user:     idefixrm
                password: Erty
                charset:  UTF8
            KLM_RM:
                driver:   pdo_mysql
                host:     kl126js8
                port:     null
                dbname:   KLM_RM
                user:     spl01001
                password: Vencodrop2
                charset:  UTF8
        
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        #auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        #metadata_cache_driver: apc
        #result_cache_driver: apc
        #query_cache_driver: apc
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       CSI_DEV
                mappings:
                    DBORMCSIBundle: ~
            CSI_OLD:
                connection:       CSI_OLD
                mappings:
                    DBORMOLDCSIBundle: ~
            KLM_RM:
                connection:       KLM_RM
                mappings:
                    DBORMKLMBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#all:
#  .settings:
#    use_database: false

sensio_framework_extra:
    view:
        annotations: false
        
