<?php

namespace Proxies\__CG__\DBORM\CSIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tbltypeprofil extends \DBORM\CSIBundle\Entity\Tbltypeprofil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'typeprofil', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'conn');
        }

        return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'typeprofil', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tbltypeprofil' . "\0" . 'conn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tbltypeprofil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkId', array());

        return parent::getPkId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeprofil($typeprofil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeprofil', array($typeprofil));

        return parent::setTypeprofil($typeprofil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeprofil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeprofil', array());

        return parent::getTypeprofil();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllTypes', array());

        return parent::getAllTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbUserByType($type_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbUserByType', array($type_id));

        return parent::getNbUserByType($type_id);
    }

    /**
     * {@inheritDoc}
     */
    public function addType($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addType', array($label));

        return parent::addType($label);
    }

    /**
     * {@inheritDoc}
     */
    public function deleteGroup($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteGroup', array($id));

        return parent::deleteGroup($id);
    }

}
