Tblstatus:
    type: entity
    table: TblStatus
    id:
        pkId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: PK_id
            generator:
                strategy: IDENTITY
    fields:
        labelstatus:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: LabelStatus
    lifecycleCallbacks: {  }
