<?php

namespace Proxies\__CG__\DBORM\CSIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tblfptcontain extends \DBORM\CSIBundle\Entity\Tblfptcontain implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalgrossweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxlooseWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxlooseVol', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'narWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'onhWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'naronhWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'narPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'onhPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'naronhPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'scbavg', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'fkFlightnumber');
        }

        return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'totalgrossweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofweight', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'opticofpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxlooseWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'sdxlooseVol', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'narWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'onhWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'naronhWgt', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'narPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'onhPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'naronhPour', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskpmd', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskpld', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'dskake', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'scbavg', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptcontain' . "\0" . 'fkFlightnumber');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tblfptcontain $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkId', array());

        return parent::getPkId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalweight($totalweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalweight', array($totalweight));

        return parent::setTotalweight($totalweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalweight', array());

        return parent::getTotalweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalpmd($totalpmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalpmd', array($totalpmd));

        return parent::setTotalpmd($totalpmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalpmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalpmd', array());

        return parent::getTotalpmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalpld($totalpld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalpld', array($totalpld));

        return parent::setTotalpld($totalpld);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalpld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalpld', array());

        return parent::getTotalpld();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalake($totalake)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalake', array($totalake));

        return parent::setTotalake($totalake);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalake', array());

        return parent::getTotalake();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalgrossweight($totalgrossweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalgrossweight', array($totalgrossweight));

        return parent::setTotalgrossweight($totalgrossweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalgrossweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalgrossweight', array());

        return parent::getTotalgrossweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpticofweight($opticofweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpticofweight', array($opticofweight));

        return parent::setOpticofweight($opticofweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpticofweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpticofweight', array());

        return parent::getOpticofweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpticofpmd($opticofpmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpticofpmd', array($opticofpmd));

        return parent::setOpticofpmd($opticofpmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpticofpmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpticofpmd', array());

        return parent::getOpticofpmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpticofake($opticofake)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpticofake', array($opticofake));

        return parent::setOpticofake($opticofake);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpticofake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpticofake', array());

        return parent::getOpticofake();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpticofpld($opticofpld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpticofpld', array($opticofpld));

        return parent::setOpticofpld($opticofpld);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpticofpld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpticofpld', array());

        return parent::getOpticofpld();
    }

    /**
     * {@inheritDoc}
     */
    public function setSdxake($sdxake)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSdxake', array($sdxake));

        return parent::setSdxake($sdxake);
    }

    /**
     * {@inheritDoc}
     */
    public function getSdxake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSdxake', array());

        return parent::getSdxake();
    }

    /**
     * {@inheritDoc}
     */
    public function setSdxlooseWgt($sdxlooseWgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSdxlooseWgt', array($sdxlooseWgt));

        return parent::setSdxlooseWgt($sdxlooseWgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSdxlooseWgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSdxlooseWgt', array());

        return parent::getSdxlooseWgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSdxlooseVol($sdxlooseVol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSdxlooseVol', array($sdxlooseVol));

        return parent::setSdxlooseVol($sdxlooseVol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSdxlooseVol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSdxlooseVol', array());

        return parent::getSdxlooseVol();
    }

    /**
     * {@inheritDoc}
     */
    public function setNarWgt($narWgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNarWgt', array($narWgt));

        return parent::setNarWgt($narWgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNarWgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNarWgt', array());

        return parent::getNarWgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnhWgt($onhWgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnhWgt', array($onhWgt));

        return parent::setOnhWgt($onhWgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnhWgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnhWgt', array());

        return parent::getOnhWgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaronhWgt($naronhWgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaronhWgt', array($naronhWgt));

        return parent::setNaronhWgt($naronhWgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaronhWgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaronhWgt', array());

        return parent::getNaronhWgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setNarPour($narPour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNarPour', array($narPour));

        return parent::setNarPour($narPour);
    }

    /**
     * {@inheritDoc}
     */
    public function getNarPour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNarPour', array());

        return parent::getNarPour();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnhPour($onhPour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnhPour', array($onhPour));

        return parent::setOnhPour($onhPour);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnhPour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnhPour', array());

        return parent::getOnhPour();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaronhPour($naronhPour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaronhPour', array($naronhPour));

        return parent::setNaronhPour($naronhPour);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaronhPour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaronhPour', array());

        return parent::getNaronhPour();
    }

    /**
     * {@inheritDoc}
     */
    public function setDskpmd($dskpmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDskpmd', array($dskpmd));

        return parent::setDskpmd($dskpmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDskpmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDskpmd', array());

        return parent::getDskpmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDskpld($dskpld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDskpld', array($dskpld));

        return parent::setDskpld($dskpld);
    }

    /**
     * {@inheritDoc}
     */
    public function getDskpld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDskpld', array());

        return parent::getDskpld();
    }

    /**
     * {@inheritDoc}
     */
    public function setDskake($dskake)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDskake', array($dskake));

        return parent::setDskake($dskake);
    }

    /**
     * {@inheritDoc}
     */
    public function getDskake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDskake', array());

        return parent::getDskake();
    }

    /**
     * {@inheritDoc}
     */
    public function setScbavg($scbavg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScbavg', array($scbavg));

        return parent::setScbavg($scbavg);
    }

    /**
     * {@inheritDoc}
     */
    public function getScbavg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScbavg', array());

        return parent::getScbavg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkFlightnumber(\DBORM\CSIBundle\Entity\Tblfptflights $fkFlightnumber = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkFlightnumber', array($fkFlightnumber));

        return parent::setFkFlightnumber($fkFlightnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkFlightnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkFlightnumber', array());

        return parent::getFkFlightnumber();
    }

}
