<?php

namespace Proxies\__CG__\DBORM\OLDCSIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tblfptschedule extends \DBORM\OLDCSIBundle\Entity\Tblfptschedule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'sector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'subsector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'flight', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'origin', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'routing', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'typeavion', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'dow', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'nbj', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'etd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pmd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pld', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'ake', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'debPeriode', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'finPeriode', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'instructions', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'fdvtime', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'maxpayload', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volmd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volld', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'mailSubsector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'mailAssistant', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'wgtLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pldLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'len20ft');
        }

        return array('__isInitialized__', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'sector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'subsector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'flight', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'origin', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'routing', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'typeavion', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'dow', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'nbj', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'etd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pmd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pld', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'ake', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'debPeriode', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'finPeriode', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'instructions', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'fdvtime', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'maxpayload', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volmd', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volld', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'mailSubsector', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'mailAssistant', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'wgtLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'volLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'pldLse', '' . "\0" . 'DBORM\\OLDCSIBundle\\Entity\\Tblfptschedule' . "\0" . 'len20ft');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tblfptschedule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', array($sector));

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getSector();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', array());

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubsector($subsector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubsector', array($subsector));

        return parent::setSubsector($subsector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubsector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubsector', array());

        return parent::getSubsector();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlight($flight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlight', array($flight));

        return parent::setFlight($flight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlight', array());

        return parent::getFlight();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigin($origin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigin', array($origin));

        return parent::setOrigin($origin);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigin', array());

        return parent::getOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function setRouting($routing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRouting', array($routing));

        return parent::setRouting($routing);
    }

    /**
     * {@inheritDoc}
     */
    public function getRouting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRouting', array());

        return parent::getRouting();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeavion($typeavion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeavion', array($typeavion));

        return parent::setTypeavion($typeavion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeavion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeavion', array());

        return parent::getTypeavion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDow($dow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDow', array($dow));

        return parent::setDow($dow);
    }

    /**
     * {@inheritDoc}
     */
    public function getDow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDow', array());

        return parent::getDow();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbj($nbj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbj', array($nbj));

        return parent::setNbj($nbj);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbj', array());

        return parent::getNbj();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtd($etd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtd', array($etd));

        return parent::setEtd($etd);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtd', array());

        return parent::getEtd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPmd($pmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPmd', array($pmd));

        return parent::setPmd($pmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPmd', array());

        return parent::getPmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPld($pld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPld', array($pld));

        return parent::setPld($pld);
    }

    /**
     * {@inheritDoc}
     */
    public function getPld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPld', array());

        return parent::getPld();
    }

    /**
     * {@inheritDoc}
     */
    public function setAke($ake)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAke', array($ake));

        return parent::setAke($ake);
    }

    /**
     * {@inheritDoc}
     */
    public function getAke()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAke', array());

        return parent::getAke();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebPeriode($debPeriode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebPeriode', array($debPeriode));

        return parent::setDebPeriode($debPeriode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebPeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebPeriode', array());

        return parent::getDebPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinPeriode($finPeriode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinPeriode', array($finPeriode));

        return parent::setFinPeriode($finPeriode);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinPeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinPeriode', array());

        return parent::getFinPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstructions($instructions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstructions', array($instructions));

        return parent::setInstructions($instructions);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstructions', array());

        return parent::getInstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function setFdvtime($fdvtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFdvtime', array($fdvtime));

        return parent::setFdvtime($fdvtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getFdvtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFdvtime', array());

        return parent::getFdvtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxpayload($maxpayload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxpayload', array($maxpayload));

        return parent::setMaxpayload($maxpayload);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxpayload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxpayload', array());

        return parent::getMaxpayload();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolmd($volmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolmd', array($volmd));

        return parent::setVolmd($volmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolmd', array());

        return parent::getVolmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolld($volld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolld', array($volld));

        return parent::setVolld($volld);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolld', array());

        return parent::getVolld();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailSubsector($mailSubsector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailSubsector', array($mailSubsector));

        return parent::setMailSubsector($mailSubsector);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailSubsector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailSubsector', array());

        return parent::getMailSubsector();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailAssistant($mailAssistant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailAssistant', array($mailAssistant));

        return parent::setMailAssistant($mailAssistant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailAssistant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailAssistant', array());

        return parent::getMailAssistant();
    }

    /**
     * {@inheritDoc}
     */
    public function setWgtLse($wgtLse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWgtLse', array($wgtLse));

        return parent::setWgtLse($wgtLse);
    }

    /**
     * {@inheritDoc}
     */
    public function getWgtLse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWgtLse', array());

        return parent::getWgtLse();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolLse($volLse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolLse', array($volLse));

        return parent::setVolLse($volLse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolLse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolLse', array());

        return parent::getVolLse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPldLse($pldLse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPldLse', array($pldLse));

        return parent::setPldLse($pldLse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPldLse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPldLse', array());

        return parent::getPldLse();
    }

    /**
     * {@inheritDoc}
     */
    public function setLen20ft($len20ft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLen20ft', array($len20ft));

        return parent::setLen20ft($len20ft);
    }

    /**
     * {@inheritDoc}
     */
    public function getLen20ft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLen20ft', array());

        return parent::getLen20ft();
    }

}
