<?php

namespace Proxies\__CG__\DBORM\CSIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tblfptrouting extends \DBORM\CSIBundle\Entity\Tblfptrouting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportOrigin', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest1', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest2', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest3', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest4', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest5', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest6', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest7', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkFlightnumber');
        }

        return array('__isInitialized__', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'pkId', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportOrigin', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest1', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest2', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest3', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest4', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest5', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest6', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkAirportDest7', '' . "\0" . 'DBORM\\CSIBundle\\Entity\\Tblfptrouting' . "\0" . 'fkFlightnumber');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tblfptrouting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkId', array());

        return parent::getPkId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportOrigin(\DBORM\CSIBundle\Entity\Tblairport $fkAirportOrigin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportOrigin', array($fkAirportOrigin));

        return parent::setFkAirportOrigin($fkAirportOrigin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportOrigin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportOrigin', array());

        return parent::getFkAirportOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest1(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest1', array($fkAirportDest1));

        return parent::setFkAirportDest1($fkAirportDest1);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest1', array());

        return parent::getFkAirportDest1();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest2(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest2', array($fkAirportDest2));

        return parent::setFkAirportDest2($fkAirportDest2);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest2', array());

        return parent::getFkAirportDest2();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest3(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest3 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest3', array($fkAirportDest3));

        return parent::setFkAirportDest3($fkAirportDest3);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest3', array());

        return parent::getFkAirportDest3();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest4(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest4 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest4', array($fkAirportDest4));

        return parent::setFkAirportDest4($fkAirportDest4);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest4', array());

        return parent::getFkAirportDest4();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest5(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest5 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest5', array($fkAirportDest5));

        return parent::setFkAirportDest5($fkAirportDest5);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest5', array());

        return parent::getFkAirportDest5();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest6(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest6 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest6', array($fkAirportDest6));

        return parent::setFkAirportDest6($fkAirportDest6);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest6', array());

        return parent::getFkAirportDest6();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAirportDest7(\DBORM\CSIBundle\Entity\Tblairport $fkAirportDest7 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAirportDest7', array($fkAirportDest7));

        return parent::setFkAirportDest7($fkAirportDest7);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAirportDest7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAirportDest7', array());

        return parent::getFkAirportDest7();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkFlightnumber(\DBORM\CSIBundle\Entity\Tblfptflights $fkFlightnumber = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkFlightnumber', array($fkFlightnumber));

        return parent::setFkFlightnumber($fkFlightnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkFlightnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkFlightnumber', array());

        return parent::getFkFlightnumber();
    }

}
